# When /annihilation start is run, the delay before starting phase 1 in seconds
start-delay: 120

# Phase length in seconds (Phase 5 is perpetual)
phase-period: 600

# When the game ends, the delay before resetting the game
restart-delay: 120

# Stat system: "flatfile" for yml or "sql" for MySQL
stats: flatfile

MySQL:
    port: 3306
    user: mc_
    pass: mc_
    host: localhost
    name: annihilation
    
# Display Roman Numerals for phase numbers
roman: true

# Auto updater
allowUpdater: true

# Amount of players required to start the game
requiredToStart: 2

# Build Distance from Nexus
build: 5

# Delay in minutes to respawn the bosses after death
bossRespawnDelay: 10

# Enable the custom MOTD
enableMotd: true

# The last phase players can join a team
lastJoinPhase: 2

# Custom MOTD - Values you can use
# %PHASE% %TIME% %PLAYERCOUNT% %MAXPLAYERS%
# %GREENNEXUS% %REDNEXUS% %BLUENEXUS% %YELLOWNEXUS%
# %GREENCOUNT% %REDCOUNT% %BLUECOUNT% %YELLOWCOUNT% 
motd: '&3Phase: &b%PHASE% &8| &bTime: &a%TIME%'

# Un-comment the below to enable
# NOTICE: If enabled the game WILL NOT AUTO RESTART.
# commandsToRunAtEndGame:
# - "stop"